#!/usr/bin/awk -f
# $Id: min,v 1.1 2003/10/03 17:27:47 elmar Exp $

BEGIN {
	first=1
}
/[0-9]/{
	if (first) {
		for (i=1; i<=NF; i++) {
			if (match($i,/[0-9][0-9]*/)) {
				y[i] = $i
				first = 0
			}
		}
	} else {
		for (i=1; i<=NF; i++) {
			if($i<y[i])	y[i]=$i
		}
	}
}
END {
	for (i=1; i<length(y); i++) {
		printf("%f ",y[i])
	}
	print y[length(y)]
}

#awk 'BEGIN{first=1}
#{
#	if (first) {
#		y = $1
#		first = 0
#	} else
#		if($1<y) y=$1
#}END{print y}'
#
#
